"diameter_electrode_outer"= 15mm
"width_wing"= 5mm
"rad_curve"= "diameter_electrode_outer" / 2
"length_wing"= 10mm
"range_electrode_move_horizontal"= ( "length_wing" / 2 ) * 66
"length_slit_horizontal"= "diameter_electrode_outer" + "range_electrode_move_horizontal"
"width_frame"= "diameter_electrode_outer" + "width_wing" * 2
"height_frame" = 1.9mm
"diameter_fluid_tank_outer" = 60mm
"width_frame_support"= 10mm
"D1@Fillet2"="rad_curve"
"range_electrode_move_vertical" = ( "length_wing" / 2 ) * 75
"length_slit_vertical"= "diameter_electrode_outer" + "range_electrode_move_vertical"
"circumference_head"= 600mm
"range_electrode_move_front" = "circumference_head" * 3.5 / 10
"length_slit_front"= "range_electrode_move_front" + "diameter_electrode_outer"
"width_connect"= 2mm
"height_connect"= "height_frame" / 2
"D1@Sketch6"="diameter_electrode_outer"+"width_wing"*2
"D2@Sketch6"="length_slit_vertical"
"D3@Sketch6"="length_wing"/2
"D4@Sketch6"="rad_curve"
"D6@Sketch6"="range_electrode_move_vertical"/8
"D7@Sketch6"="range_electrode_move_vertical"/4
"D1@Sketch7"="width_connect"
"D1@Boss-Extrude5"="height_connect"
"D1@Boss-Extrude4"="height_frame"
