"diameter_ring_outer"= 40mm
"height_ring" = 15mm
"D1@Sketch1"="diameter_ring_outer"
"D2@Sketch1"="width_wall"*2
"D1@Boss-Extrude1"="height_ring"
"D1@Sketch2"="diameter_tube"
"dist_tube_bottom"= 1mm
"D2@Sketch2"="diameter_tube"/2+"dist_tube_bottom"
"diameter_ring_inner" = 25mm
"D1@Sketch3"="diameter_ring_inner"
"D3@Sketch3"="width_wall"
"length_spring_expand"= 15mm
"length_spring_compress"= 7.5mm
"D1@Boss-Extrude11" = "width_wall"
"height_slit"= 5mm
"D1@Cut-Extrude2"="height_slit"
"diameter_spring_inner"= 3.5mm
"D2@Sketch3"="width_wall"
"length_slit_inner"= 1.5mm
"num_electrodes"= 19
"D1@CirPattern1"="num_electrodes"
"D4@Sketch3"="num_electrodes"
"D1@CirPattern2"="num_electrodes"
"diameter_screw_Cz" = 13mm
"D1@Sketch22"="diameter_screw_Cz"
"dist_spring_center"= 7mm
"height_thread"= 2mm
"width_wall" = 1mm
"diameter_tube"= 2mm
"length_stop" = 1mm
"height_stop" = 1mm
"D1@Sketch6"="length_slit_inner"
"indent_thread"= 1mm
"D1@Sketch26"="indent_thread"
"D1@Sketch30"="length_stop"
"D1@Boss-Extrude13"="height_stop"
"D1@Sketch33"="indent_thread"
"D1@Cut-Extrude7"="height_thread"
"D1@Sketch34"="indent_thread"
"D2@Sketch34"="indent_thread"
"diameter_connect_bottom"= "diameter_ring_outer" - 5mm
"width_connect_bottom"= 2mm
"D1@Sketch37"="diameter_connect_bottom"
"D2@Sketch37"="width_connect_bottom"
