"diameter_electrode_outer"= 15mm
"height_electrode_straigth"= "height_frame" * 2 + "height_wing_individual" * 2 + "height_thread" + 1mm
"width_wall"= 1mm
"width_wing"= 5mm
"length_wing"= 10mm
"height_wing_individual"= 1mm
"height_frame"= 2mm
"offset"= 0.1mm
"height_wing_total"= "height_wing_individual" * 2 + "height_frame" - "offset"
"D1@Sketch1"="diameter_electrode_outer"
"D1@Boss-Extrude1"="height_electrode_straigth"
"D1@Sketch2"="width_wall"
"D1@Sketch3"="length_wing"
"D2@Sketch3"="width_wing"
"D1@Boss-Extrude2"="height_wing_total"
"D1@Sketch4"="height_wing_gap"
"D2@Sketch4"="diameter_electrode_outer"/2
"D1@Sketch5"="length_wing"
"D2@Sketch5"="width_wing"
"D1@Boss-Extrude3"="height_wing_total"-"height_wing_individual"
"D1@Sketch6"="diameter_electrode_outer"/2
"D2@Sketch6"="height_wing_gap"
"D2@Boss-Extrude3"="height_wing_individual"
"width_cotton_holder"= 0.5mm
"height_cotton_holder"= 1mm
"width_thread"= 1mm
"height_thread"= 4mm
"pitch_thread_large"= 1mm
"pitch_thread_small"= 0.1mm
"diameter_tube"= 2mm
"D1@Sketch22"="diameter_tube"
"D2@Sketch22"="diameter_tube"/2+"height_thread"+0.5mm
"height_electrode_chamfer"= 3mm
"D1@Sketch23"="height_electrode_chamfer"
"diameter_electrode_tip_in"= 8mm
"D2@Sketch23"="diameter_electrode_tip_in"/2
"D4@Thread1"="height_thread"
"D4@Sketch23"="width_cotton_holder"
"D5@Sketch23"="height_cotton_holder"
"D3@Sketch23"="width_wall"
"D1@Fillet2"="width_wall"
"width_dupont"= 2mm
"height_dupont"= 1.7mm
"length_dupont"= 11.5mm
"height_wing_gap"= "height_frame" + "offset" * 3
